// src/features/legal/pages/TermsPage.tsx
import React from 'react';
import { Header } from '../../../components/common/Header';
import { Footer } from '../../../components/common/Footer';

const TermsPage: React.FC = () => {
  return (
    <div className="flex flex-col min-h-screen bg-background text-foreground">
      <Header />
      <main className="flex-grow container mx-auto px-4 py-12 md:py-16">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold text-primary mb-8">Terms of Service</h1>
          <div className="prose prose-lg prose-invert text-slate-300">
            <p>Welcome to Dakshin Vaarahi ("AuraOS"). By accessing or using our platform, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree to these terms, please do not use our services.</p>
            
            <h2>1. Use of Service</h2>
            <p>AuraOS is a platform for architectural design and AI-powered analysis. You are responsible for the content you create and for complying with all applicable laws and regulations in your jurisdiction. You agree not to use the service for any illegal or unauthorized purpose.</p>

            <h2>2. AI-Generated Content</h2>
            <p>The content, designs, and analysis generated by our AI are for conceptual and informational purposes only. They are not a substitute for professional architectural, engineering, or legal advice. You are solely responsible for verifying the accuracy, safety, and compliance of any AI-generated materials before use in any real-world application.</p>
            
            <h2>3. Intellectual Property</h2>
            <p>You retain ownership of the intellectual property rights in the content you create on the platform. By using the service, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, and display the content solely for the purpose of operating and improving the service.</p>

            <h2>4. Disclaimers and Limitation of Liability</h2>
            <p>The service is provided "as is" without any warranties of any kind. We do not warrant that the service will be uninterrupted, error-free, or secure. In no event shall Dakshin Vaarahi be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or in connection with your use of the service.</p>

            <p><em>(This is a placeholder document. A complete and legally-binding Terms of Service would be required for a real-world launch.)</em></p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default TermsPage;